import type { ArmaturaDef } from './armatura';

/**
 * Historically flavoured arena beasts — venatio / damnatio spectacle.
 * Same AI brain as gladiators; kits lean rush / thrash / no real guard.
 */

export type BeastId = 'LION' | 'LEOPARD' | 'BEAR' | 'BOAR';

/** BeastDef mirrors ArmaturaDef geometry so Fighter.def() can serve either. */
export type BeastDef = Omit<ArmaturaDef, 'id'> & { id: BeastId };

export const BEASTS: Record<BeastId, BeastDef> = {
  LION: {
    id: 'LION',
    name: 'Lion',
    short: 'Leo',
    color: '#c4a35a',
    maxHealth: 140,
    maxStamina: 70,
    maxPoise: 80,
    strength: 16,
    measureMin: 28,
    measureMax: 42,
    attackRange: 40,
    attackArc: 0.9,
    guardArc: 0.05,
    turnRate: 3.4,
    moveSpeed: 88,
    strafeMul: 0.7,
    mass: 1.5,
    windup: 10,
    active: 7,
    recover: 12,
    attackCooldown: 10,
    attackStamina: 11,
    blockStaminaPerTick: 0.35,
    dodgeStamina: 8,
    dodgeDuration: 10,
    dodgeCooldown: 18,
    damageMul: 1.2,
    poiseMul: 1.15,
    guardAbsorb: 0.95,
    tipCatchRatio: 0,
    tipCatchTicks: 0,
    tipCatchResist: 0.2,
    shieldShock: 0,
    circleArcBonus: 0.1,
    clinchPanic: 0.05,
    pursueBias: 0.75,
  },
  LEOPARD: {
    id: 'LEOPARD',
    name: 'Leopard',
    short: 'Pard',
    color: '#b8860b',
    maxHealth: 95,
    maxStamina: 85,
    maxPoise: 45,
    strength: 12,
    measureMin: 26,
    measureMax: 40,
    attackRange: 38,
    attackArc: 1.0,
    guardArc: 0.04,
    turnRate: 4.2,
    moveSpeed: 96,
    strafeMul: 1.1,
    mass: 0.95,
    windup: 7,
    active: 5,
    recover: 8,
    attackCooldown: 6,
    attackStamina: 8,
    blockStaminaPerTick: 0.4,
    dodgeStamina: 6,
    dodgeDuration: 14,
    dodgeCooldown: 10,
    damageMul: 1.05,
    poiseMul: 0.9,
    guardAbsorb: 0.95,
    tipCatchRatio: 0,
    tipCatchTicks: 0,
    tipCatchResist: 0,
    shieldShock: 0,
    circleArcBonus: 0.2,
    clinchPanic: 0.15,
    pursueBias: 0.65,
  },
  BEAR: {
    id: 'BEAR',
    name: 'Bear',
    short: 'Urs',
    color: '#6b5344',
    maxHealth: 180,
    maxStamina: 55,
    maxPoise: 120,
    strength: 18,
    measureMin: 30,
    measureMax: 44,
    attackRange: 42,
    attackArc: 0.75,
    guardArc: 0.08,
    turnRate: 2.2,
    moveSpeed: 58,
    strafeMul: 0.45,
    mass: 1.85,
    windup: 16,
    active: 9,
    recover: 18,
    attackCooldown: 14,
    attackStamina: 16,
    blockStaminaPerTick: 0.25,
    dodgeStamina: 14,
    dodgeDuration: 8,
    dodgeCooldown: 28,
    damageMul: 1.3,
    poiseMul: 1.35,
    guardAbsorb: 0.9,
    tipCatchRatio: 0,
    tipCatchTicks: 0,
    tipCatchResist: 0.35,
    shieldShock: 0,
    circleArcBonus: 0,
    clinchPanic: 0.02,
    pursueBias: 0.55,
  },
  BOAR: {
    id: 'BOAR',
    name: 'Boar',
    short: 'Apr',
    color: '#5a4a3a',
    maxHealth: 110,
    maxStamina: 65,
    maxPoise: 70,
    strength: 14,
    measureMin: 24,
    measureMax: 38,
    attackRange: 36,
    attackArc: 0.7,
    guardArc: 0.06,
    turnRate: 3.0,
    moveSpeed: 78,
    strafeMul: 0.6,
    mass: 1.25,
    windup: 9,
    active: 6,
    recover: 10,
    attackCooldown: 8,
    attackStamina: 10,
    blockStaminaPerTick: 0.32,
    dodgeStamina: 9,
    dodgeDuration: 11,
    dodgeCooldown: 14,
    damageMul: 1.15,
    poiseMul: 1.2,
    guardAbsorb: 0.92,
    tipCatchRatio: 0,
    tipCatchTicks: 0,
    tipCatchResist: 0.15,
    shieldShock: 0,
    circleArcBonus: 0.05,
    clinchPanic: 0.08,
    pursueBias: 0.85,
  },
};

export const BEAST_LIST: BeastId[] = ['LION', 'LEOPARD', 'BEAR', 'BOAR'];

export function beastAsArmaturaDef(b: BeastDef): ArmaturaDef {
  return { ...b, id: 'MURMILLO' };
}
